services:
  stats:
    build:
      context: ./stats
    environment:
      DATABASE_URL: sqlite+aiosqlite:////data/events.db
    volumes:
      - stats_data:/data
    restart: unless-stopped
    networks: [appnet]

  stats-tg:
    build:
      context: ./stats-tg
    # container_name: stats-tg
    env_file: stats-tg/.env
    environment:
      DATABASE_PATH: /data/chats.db
      API_BASE_URL: http://stats:8000
      # SSL_CERT_PATH: /etc/certs/ssl.pem
      # SSL_KEY_PATH:  /etc/certs/ssl.key
    volumes:
      - stats_tg_data:/data
    ports:
      - "80:8000"
    networks: [appnet]


  vk-bot:
    build:
      context: ./vk-bot
    env_file: vk-bot/.env
    environment:
      SERVER_URL: http://stats:8000
    networks: [appnet]

networks:
  appnet: {}

volumes:
  stats_data: {}
  stats_tg_data: {}
